username = input('Введите имя:')
title = input('Заголовок заметки:')
content = input('Описание заметки:')
status =  input('Статус заметки:')
created_date = input('Дата создания заметки (в формате-01.01.2000):')
issue_date = input('Дата истечения заметки (в формате-01.01.2000):')